### ISSUE TITLE
Get current 3mf png does not work

### ISSUE THREAD

**Issue by Android1338** [synman/bambu-printer-manager#6]
I've deployed your container and all works very well but the "Get current 3mf png" (thumbnail of printing model). 

![image](https://github.com/synman/bambu-printer-manager/assets/29342292/96e95466-2299-475c-b1b4-b251f7179583)

If I'll open the missing image I receive of course the following message:
![image](https://github.com/synman/bambu-printer-manager/assets/29342292/b0d6e999-f7f5-44d8-97ca-0378b3551c99)
Link: /api/get_current_3mf_png

Is there something to fix on my site?
I've defined the following environment variables for the container:
- BAMBU_HOSTNAME
- BAMBU_ACCESS_CODE
- PRINTER_SERIAL_NUMBER

I'm using a Bambu P1S on latest firmware release 01.05.02.00.

**Comment by synman** [comment]
This is likely one of two things.

* I had a preprocessor bug related to "." characters in the filename not tied to the actual .gcode.3mf extension.  This is fixed in an up and coming build I'll be releasing in a day or two.
* The .gcode.3mf file was not uploaded by BPM.  In this scenario BPM does not have a "cached" copy of the 3mf and therefore can't find it.  I haven't decided yet if I want to go through the trouble of syncing storage between the printer and container and suggest you always upload from BPM for now as this ensures both the printer and BPM get a copy of the archive.
